export const INDEX_PAGE_URL = "/";
export const REFRESH_STATUS_TEXT = "...refresh";
export const LINK_UNDERLINE = "always";
export const VARIANT_H1 = "h1";
export const VARIANT_H3 = "h3";
export const VARIANT_H4 = "h4";
export const BUTTON_VARIANT_CONTAINED = "contained";
export const BUTTON_SIZE_MEDIUM = "medium";
export const BACK_BUTTON_TEXT = "< Back to news";
